kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs1
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
